[package]
name = "matrix-utils"
authors = ["Peter Winckles <pwinckles@pm.me>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
matrix-sdk-crypto = "0.6.0"
serde = "1.0.147"
serde_json = "1.0.87"
rpassword = "7.1.0"