name: Build

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - name: Build default
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-musl --release
          use-cross: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: filter-keys-linux-x86_64
          path: target/x86_64-unknown-linux-musl/release/filter-keys
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build default
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: filter-keys-windows-x86_64.exe
          path: target/release/filter-keys.exe
  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build default
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: filter-keys-macos-x86_64
          path: target/release/filter-keys
